apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-aqpi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-aqpi
    app.kubernetes.io/part-of: jvm-build-suite-application-xvmg
  name: jvm-build-suite-component-aqpi
  namespace: appstudio-e2e-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: jvm-build-suite-component-aqpi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: jvm-build-suite-component-aqpi
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images:c4d8b66a50384f4db58aea22bfcf3cec
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
